---
- name: DÃ©ploiement complet MikroTik
  hosts: localhost
  gather_facts: yes
  vars_files:
    - ../inventory/group_vars/all.yml

  roles:
    - mikrotik_base
    - mikrotik_network
    - mikrotik_firewall
