- name: Déployer le message d'accueil (MOTD)
  hosts: all
  become: yes
  vars:
    env_name: production
    server_name: "{{ inventory_hostname }}"

  tasks:
    - name: Générer /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
